apiVersion: v1
kind: Pod
metadata:
  name: temp-app
  labels:
    name: temp-app

spec:
  containers:
    - name: connector
      image: temp/node-connector
      imagePullPolicy: Never
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
      env:
        - name: REDIS_URL
          value: "redis://localhost:6379"
    - name: redis
      image: redis
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 6379
