apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: connector
  name: connector
spec:
  containers:
  - image: temp/node-connector
    name: connector
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
