version: "3"
services:
  connector:
    build: .
    image: temp/node-connector
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis
    ports:
      - 6379:6379
